import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

const SRC_DIR = path.join(repoRoot, 'src');
const ALL_CSS_PATH = path.join(repoRoot, 'node_modules', '@fortawesome', 'fontawesome-free', 'css', 'all.min.css');
const BRANDS_CSS_PATH = path.join(repoRoot, 'node_modules', '@fortawesome', 'fontawesome-free', 'css', 'brands.min.css');
const REGULAR_CSS_PATH = path.join(repoRoot, 'node_modules', '@fortawesome', 'fontawesome-free', 'css', 'regular.min.css');
const SOLID_CSS_PATH = path.join(repoRoot, 'node_modules', '@fortawesome', 'fontawesome-free', 'css', 'solid.min.css');
const OUTPUT_PATH = path.join(repoRoot, 'src', 'styles', 'fontawesome-subset.css');

const SOURCE_FILE_EXTENSIONS = new Set(['.html', '.js', '.css']);
const FA_TOKEN_RE = /\b(fa(?:-[a-z0-9-]+)?|fab|far|fas)\b/gi;

const NON_ICON_FA_CLASSES = new Set([
  'fa',
  'fab',
  'far',
  'fas',
  'fa-solid',
  'fa-regular',
  'fa-brands',
  'fa-classic',
  'fa-sharp',
  'fa-1x',
  'fa-2x',
  'fa-3x',
  'fa-4x',
  'fa-5x',
  'fa-6x',
  'fa-7x',
  'fa-8x',
  'fa-9x',
  'fa-10x',
  'fa-2xs',
  'fa-xs',
  'fa-sm',
  'fa-lg',
  'fa-xl',
  'fa-2xl',
  'fa-fw',
  'fa-spin',
  'fa-spin-pulse',
  'fa-pulse',
  'fa-beat',
  'fa-bounce',
  'fa-fade',
  'fa-beat-fade',
  'fa-flip',
  'fa-shake',
  'fa-rotate-90',
  'fa-rotate-180',
  'fa-rotate-270',
  'fa-flip-horizontal',
  'fa-flip-vertical',
  'fa-flip-both',
  'fa-inverse',
  'fa-stack',
  'fa-stack-1x',
  'fa-stack-2x',
  'fa-li',
  'fa-ul',
  'fa-border',
  'fa-pull-left',
  'fa-pull-right',
  'fa-sr-only',
  'fa-sr-only-focusable'
]);

function getFilesRecursively(dirPath) {
  const entries = readdirSync(dirPath);
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry);
    const stats = statSync(fullPath);

    if (stats.isDirectory()) {
      files.push(...getFilesRecursively(fullPath));
      continue;
    }

    const ext = path.extname(entry);
    if (SOURCE_FILE_EXTENSIONS.has(ext)) {
      files.push(fullPath);
    }
  }

  return files;
}

function getUsedFaClasses() {
  const files = getFilesRecursively(SRC_DIR);
  const classes = new Set();

  for (const filePath of files) {
    if (filePath === OUTPUT_PATH) continue;

    const content = readFileSync(filePath, 'utf8');
    const matches = content.match(FA_TOKEN_RE) || [];
    for (const cls of matches) {
      classes.add(cls.toLowerCase());
    }
  }

  return classes;
}

function buildIconUnicodeMap() {
  const allCss = readFileSync(ALL_CSS_PATH, 'utf8');
  const map = new Map();

  const ruleRe = /([^{}]+)\{content:"\\([0-9a-f]+)"\}/gi;
  let match = null;
  while ((match = ruleRe.exec(allCss)) !== null) {
    const selectors = match[1];
    const unicode = match[2].toLowerCase();

    const selectorItems = selectors.split(',');
    for (const selector of selectorItems) {
      const iconMatch = selector.match(/\.fa-([a-z0-9-]+):before/i);
      if (!iconMatch) continue;
      const className = `fa-${iconMatch[1].toLowerCase()}`;
      map.set(className, unicode);
    }
  }

  return map;
}

function extractFontFaceBlocks(cssPath) {
  const css = readFileSync(cssPath, 'utf8');
  const matches = css.match(/@font-face\{[^}]+\}/gi) || [];
  return matches.map((block) =>
    block.replace(
      /url\(\.\.\/webfonts\/([^\)]+)\)/gi,
      'url("@fortawesome/fontawesome-free/webfonts/$1")'
    )
  );
}

function buildSubsetCss(iconClasses, iconMap) {
  const missing = [];
  const iconRules = [];

  for (const iconClass of iconClasses) {
    const unicode = iconMap.get(iconClass);
    if (!unicode) {
      missing.push(iconClass);
      continue;
    }
    iconRules.push(`.${iconClass}:before{content:"\\${unicode}"}`);
  }

  if (missing.length > 0) {
    throw new Error(`Missing icon mappings: ${missing.join(', ')}`);
  }

  const fontFaces = [
    ...extractFontFaceBlocks(BRANDS_CSS_PATH),
    ...extractFontFaceBlocks(REGULAR_CSS_PATH),
    ...extractFontFaceBlocks(SOLID_CSS_PATH)
  ];

  return [
    '/* Auto-generated by scripts/generate_fa_subset.mjs. Do not edit directly. */',
    '/* stylelint-disable font-family-no-missing-generic-family-keyword */',
    ...fontFaces,
    '.fa,.fa-brands,.fa-classic,.fa-regular,.fa-sharp,.fa-solid,.fab,.far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:var(--fa-display,inline-block);font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}',
    '.fa,.fa-classic,.fa-regular,.fa-solid,.far,.fas{font-family:"Font Awesome 6 Free"}',
    '.fa-brands,.fab{font-family:"Font Awesome 6 Brands"}',
    '.fa,.fa-solid,.fas{font-weight:900}',
    '.fa-regular,.far{font-weight:400}',
    '.fa-brands,.fab{font-weight:400}',
    ...iconRules.sort(),
    ''
  ].join('\n');
}

function main() {
  const usedClasses = getUsedFaClasses();
  const usedIconClasses = [...usedClasses]
    .filter((cls) => cls.startsWith('fa-'))
    .filter((cls) => !NON_ICON_FA_CLASSES.has(cls))
    .sort();

  const iconMap = buildIconUnicodeMap();
  const subsetCss = buildSubsetCss(usedIconClasses, iconMap);

  writeFileSync(OUTPUT_PATH, subsetCss, 'utf8');

  console.log(`Generated ${path.relative(repoRoot, OUTPUT_PATH)} with ${usedIconClasses.length} icon rules.`);
}

main();